[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jazztrainer"
version = "0.0.1"
description = "A jazz training application"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []
license = {text = "MIT"}
authors = [
    {name = "Andrea Pasquino", email = "Andrea.Pasquino@insight.com"}
]


[tool.briefcase]
project_name = "Jazz Trainer"
bundle = "com.example"
version = "0.0.1"
description = "A jazz training application"
sources = ["src/jazztrainer"]

[tool.briefcase.app.jazztrainer]
formal_name = "Jazz Trainer"
description = "A jazz training application"
bundle = "com.example"
url = "https://github.com/yourusername/jazztrainer"
author = "Andrea Pasquino"
author_email = "Andrea.Pasquino@insight.com"
license = "MIT"

[tool.briefcase.app.jazztrainer.linux]
requires = []

[tool.briefcase.app.jazztrainer.windows]
requires = []

[tool.briefcase.app.jazztrainer.macos]
requires = []

[tool.briefcase.app.jazztrainer.android]
requires = []
